FROM maven:3.8.3-openjdk-17 as builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package -DskipTests

FROM tomcat:10.0

EXPOSE 8080

COPY --from=builder /app/target/shaggybeavers.war /usr/local/tomcat/webapps/ROOT.war
